// Code generated by Kitex v0.12.0. DO NOT EDIT.

package goodsservice

import (
	"context"
	"errors"
	home "eshop_main/kitex_gen/eshop/home"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetOneSku": kitex.NewMethodInfo(
		getOneSkuHandler,
		newGoodsServiceGetOneSkuArgs,
		newGoodsServiceGetOneSkuResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MGetSku": kitex.NewMethodInfo(
		mGetSkuHandler,
		newGoodsServiceMGetSkuArgs,
		newGoodsServiceMGetSkuResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	goodsServiceServiceInfo                = NewServiceInfo()
	goodsServiceServiceInfoForClient       = NewServiceInfoForClient()
	goodsServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return goodsServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return goodsServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return goodsServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "goodsService"
	handlerType := (*home.GoodsService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "home",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.0",
		Extra:           extra,
	}
	return svcInfo
}

func getOneSkuHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*home.GoodsServiceGetOneSkuArgs)
	realResult := result.(*home.GoodsServiceGetOneSkuResult)
	success, err := handler.(home.GoodsService).GetOneSku(ctx, realArg.Sku)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGoodsServiceGetOneSkuArgs() interface{} {
	return home.NewGoodsServiceGetOneSkuArgs()
}

func newGoodsServiceGetOneSkuResult() interface{} {
	return home.NewGoodsServiceGetOneSkuResult()
}

func mGetSkuHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*home.GoodsServiceMGetSkuArgs)
	realResult := result.(*home.GoodsServiceMGetSkuResult)
	success, err := handler.(home.GoodsService).MGetSku(ctx, realArg.Sku)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGoodsServiceMGetSkuArgs() interface{} {
	return home.NewGoodsServiceMGetSkuArgs()
}

func newGoodsServiceMGetSkuResult() interface{} {
	return home.NewGoodsServiceMGetSkuResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetOneSku(ctx context.Context, sku string) (r *home.GetOneSkuResponse, err error) {
	var _args home.GoodsServiceGetOneSkuArgs
	_args.Sku = sku
	var _result home.GoodsServiceGetOneSkuResult
	if err = p.c.Call(ctx, "GetOneSku", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MGetSku(ctx context.Context, sku *home.MGetSkuRequest) (r *home.MGetSkuResponse, err error) {
	var _args home.GoodsServiceMGetSkuArgs
	_args.Sku = sku
	var _result home.GoodsServiceMGetSkuResult
	if err = p.c.Call(ctx, "MGetSku", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
