name: Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
  
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: zym1614511838@gmail.com
          password: zhongyiming2003

      # 使用 Buildx 构建镜像并缓存层
      - name: 构建镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: registry.cn-hangzhou.aliyuncs.com/lazyyy1/eshop_main:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: 连接阿里云
        run:
          docker login -u aliyun2526497059 -p zhongyiming2003 registry.cn-hangzhou.aliyuncs.com;
          docker push registry.cn-hangzhou.aliyuncs.com/lazyyy1/eshop_main;

  deployment:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 更新服务器
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 117.72.72.114
          username: root
          password: F1ly6kT?
          port: 22
          script: |
            docker stop eshop_main || true
            docker rm eshop_main || true
            docker login -u aliyun2526497059 -p zhongyiming2003 registry.cn-hangzhou.aliyuncs.com
            docker pull registry.cn-hangzhou.aliyuncs.com/lazyyy1/eshop_main:latest
            docker run -d --name eshop_main -p 20000:8888 --network 47bce5c74f589f4867dbd57e9ca9f808_env-network registry.cn-hangzhou.aliyuncs.com/lazyyy1/eshop_main:latest